version: "3.9"

networks:
  chatnet:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    networks: [chatnet]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on: [redis, mongodb]
    expose: ["3000"]      # лишаємо лише expose, бо LB слухає всередині
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      chatnet:
        aliases:
          - api           # ← dns‑alias: api → один із server‑інстансів

  client:
    build: ./client
    environment:
      # браузер у середині контейнера «client» стукає до LB через внутр. DNS‑ім’я
      - VITE_API_BASE=
    networks: [ chatnet ]
    expose: ["80"] # лишаємо лише expose, бо LB слухає всередині
    depends_on: [server]

  lb:
    image: nginx:1.25-alpine
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"           # для хоста
    depends_on: [server, client, mongodb]
    networks: [chatnet]

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks: [chatnet]
