services:
  redis:
    container_name: redis-like
    build:
      context: .
      dockerfile: Dockerfile.redis
    command: npm run redis-like:start
    networks:
      - "internal"

  kv-server:
    container_name: kv-server
    build:
      context: .
      dockerfile: Dockerfile.kv
    networks:
      - "internal"
    ports:
      - "8080:3000"
    environment:
      REDIS_URL: http://redis:4000

networks:
  internal:
    driver: bridge
