FROM node:lts-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY kv-server ./kv-server
RUN npm prune --production

FROM node:lts-alpine
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/kv-server ./kv-server

WORKDIR /app/kv-server

EXPOSE 3000
CMD ["node", "server.ts"]
